/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  injectedFromSynthesis?: boolean;
}

export interface JournalEntry {
  id: string;
  content: string;
  timestamp: string;
  sentiment?: string;
  keyIssues?: string[];
}

export interface RelationalPassport {
  archetype: string;          // e.g. "Clarity Pursuer"
  attachmentStyle: string;    // e.g. "Anxious-Preoccupied"
  primaryShield: string;      // e.g. "Shield of Procedural Detail"
  growthAntidote: string;     // e.g. "Somatic Co-regulation First"
  verbalPacing: number;       // score 1-10
  assetPacing: number;        // score 1-10
  domesticPacing: number;     // score 1-10
  vulnerabilityStyle: number; // score 1-10
  confirmedByUser: boolean;
}

export interface PartnerProfile {
  name: string;
  role: string;
  journalEntries: JournalEntry[];
  chatHistory: ChatMessage[];
  coreValues: string[];
  hiddenInjectedReflections: string[]; // generated by synthesis, invisible to the partner as a "source", but used as prompt injections or subtle guides
  reflectionRatings?: Record<string, number>; // map injection prompt to resonance score (1-10) to feed back into self-learning loop
  unlockedExercises?: string[]; // dynamically unlocked helper tools, e.g., ["shadow-mismatch", "nervous-system-map"]
  passport?: RelationalPassport;
}

export interface ConflictContext {
  topic: string; // e.g. "Finances", "Career Pacing", "Family Boundaries"
  description: string;
  partnerA_view: string;
  partnerB_view: string;
  // Specific financial or worksheet details if applicable
  worksheetData?: {
    partnerA_budget: { label: string; amount: number }[];
    partnerB_budget: { label: string; amount: number }[];
  };
  revMode?: 'existing' | 'single' | 'fresh-c';
}

export interface SynthesisReport {
  timestamp: string;
  overview: string;
  // Non-blaming diagnostic themes
  coreClashThemes: {
    title: string;
    description: string;
    mismatchType: string; // e.g., "Pacing difference", "Value mismatch", "Communication gap"
  }[];
  // Subtly highlighted contradictions (with care and understanding)
  contradictionInsights: {
    topic: string;
    insight: string; // e.g., "Partner A seeks certainty about tomorrow, while Partner B seeks freedom of action."
    mediationStrategy: string; // instructions for how the AI companion should steer them
  }[];
  // Specific subtle reflection prompts to inject into each companion's view
  partnerA_injections: string[];
  partnerB_injections: string[];
  // Suggestions on medium and timing
  suggestedDialogueMediums: {
    type: string; // e.g., "Structured 20-min walking conversation", "Written values exchanging"
    reason: string;
    agenda: string[];
    gcalLinkA?: string;
    gcalLinkB?: string;
  }[];
  // Value Matrix Chart data
  valueMatrix: {
    valueName: string;
    partnerARating: number; // 0-10
    partnerBRating: number; // 0-10
    definition: string;
    suggestedPartnerARating?: number; // suggested based on unedited logs to prevent self-declared contamination
    suggestedPartnerBRating?: number; // suggested based on unedited logs to prevent self-declared contamination
    insightAnalysis?: string; // explanation of contamination or discrepancy between report and unedited logs
  }[];
  progressTrend?: {
    date: string; // E.g., 'May 20', 'Jun 1', 'Jun 10', 'Jun 15'
    alignmentScore: number; // 0 to 100 percentage of overall value alignment
    sentimentA: number; // 0 to 10 rating of Alex's private journal sentiment
    sentimentB: number; // 0 to 10 rating of Taylor's private journal sentiment
    clashIntensity: number; // 0 to 10 rating of relationship friction
  }[];
}

export interface RelationshipAppState {
  partnerA: PartnerProfile;
  partnerB: PartnerProfile;
  conflictContext: ConflictContext;
  synthesis: SynthesisReport | null;
  isSynthesizing: boolean;
  scheduledDialogues: ScheduledDialogue[];
}

export interface ScheduledDialogue {
  id: string;
  title: string;
  startTime: string;
  durationMinutes: number;
  format: string;
  description: string;
  calendarLink: string;
}

export interface ConduitMessage {
  id: string;
  senderKey: 'partnerA' | 'partnerB';
  senderName: string;
  content: string;
  timestamp: string;
  isAiGenerated: boolean;
  originalRawDraft?: string;
}

